name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron:  '* 6-23 * * *'

jobs:
  check_for_new:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.16'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: scan
        id: scan
        run: python main.py
      - name: create an issue
        if: ${{ steps.scan.outputs.FOUND_UPDATE == 'True' }}
        uses: dblock/create-a-github-issue@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          COUNT: ${{ steps.scan.outputs.COUNT }}
        with:
          filename: .github/ISSUE_TEMPLATE/new_message.md