name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron:  '* 7-22 * * *'

jobs:
  check_for_new:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.9'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: scan
        id: scan
        run: python main.py
